"""complete_initial_schema

Revision ID: 8da089ec3771
Revises: 
Create Date: 2026-05-16 00:15:16.191245

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = '8da089ec3771'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', app.models.SafeString(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('first_name', app.models.SafeString(length=64), nullable=False),
    sa.Column('last_name', app.models.SafeString(length=64), nullable=False),
    sa.Column('gender', app.models.SafeString(length=16), nullable=True),
    sa.Column('postcode', sa.Integer(), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('instagram', app.models.SafeString(length=100), nullable=True),
    sa.Column('sport_1', app.models.SafeString(length=64), nullable=True),
    sa.Column('sport_2', app.models.SafeString(length=64), nullable=True),
    sa.Column('sport_3', app.models.SafeString(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('event_name', app.models.SafeString(length=128), nullable=False),
    sa.Column('sport', sa.String(length=64), nullable=False),
    sa.Column('location', app.models.SafeString(length=128), nullable=False),
    sa.Column('postcode', sa.Integer(), nullable=False),
    sa.Column('description', app.models.SafeText(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('spots_total', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('friend_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matching',
    sa.Column('matching_id', sa.Integer(), nullable=False),
    sa.Column('user_a_id', sa.Integer(), nullable=False),
    sa.Column('user_b_id', sa.Integer(), nullable=False),
    sa.Column('response_a', sa.String(length=8), nullable=True),
    sa.Column('response_b', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('matching_id')
    )
    op.create_table('attendees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_host', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendees')
    op.drop_table('matching')
    op.drop_table('friends')
    op.drop_table('friend_requests')
    op.drop_table('events')
    op.drop_table('users')
    # ### end Alembic commands ###
